ALTER TABLE "Guardian" ADD COLUMN "deletedAt" TIMESTAMP(3);
ALTER TABLE "School" ADD COLUMN "deletedAt" TIMESTAMP(3);
ALTER TABLE "Driver" ADD COLUMN "deletedAt" TIMESTAMP(3);
ALTER TABLE "Van" ADD COLUMN "deletedAt" TIMESTAMP(3);
ALTER TABLE "Student" ADD COLUMN "deletedAt" TIMESTAMP(3);
ALTER TABLE "Payment" ADD COLUMN "deletedAt" TIMESTAMP(3);
